<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
    $exclude = [
        'sinch_summary_title_1', 'sinch_summary_value_1',
        'sinch_summary_title_2', 'sinch_summary_value_2',
        'sinch_summary_title_3', 'sinch_summary_value_3',
        'sinch_summary_title_4', 'sinch_summary_value_4'
    ];
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <tbody>
            <?php // Show the summary features first (they're "summary" features...)
            for ($i = 1; $i <= 4; $i++):
                $title = $_product->getData("sinch_summary_title_{$i}");
                $value = $_product->getData("sinch_summary_value_{$i}");
                if (empty($title) || empty($value)) continue; ?>
                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml($title) ?></th>
                    <td class="col data" data-th="<?= $block->escapeHtmlAttr($title) ?>"><?= /* @noEscape */ $_helper->productAttribute($_product, $value, "sinch_summary_value_{$i}") ?></td>
                </tr>
            <?php endfor;
            $_additional = $block->getAdditionalData($exclude);
            foreach ($_additional as $_data):
                $label = $block->escapeHtml($_data['label']);
                if ($_data['code'] === 'pdf_url' || $_data['code'] == 'sinch_manuals' || $_data['code'] == 'sinch_videos'): ?>
                    <tr>
                        <th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
                        <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>">
                            <?php 
                                $urls = $_helper->productAttribute($_product, $_data['value'], $_data['code']);
                                $urlsArray = explode(";", $urls);
                                $dataCodeLabel = '';
                                $dataIcon = '';
                                switch($_data['code']){
                                    case 'sinch_manuals':
                                        $dataCodeLabel = 'View Manual';
                                        $dataIcon = '<svg class="icon-attribute" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M280 24c0-13.3-10.7-24-24-24s-24 10.7-24 24l0 270.1-95-95c-9.4-9.4-24.6-9.4-33.9 0s-9.4 24.6 0 33.9L239 369c9.4 9.4 24.6 9.4 33.9 0L409 233c9.4-9.4 9.4-24.6 0-33.9s-24.6-9.4-33.9 0l-95 95L280 24zM128.8 304L64 304c-35.3 0-64 28.7-64 64l0 80c0 35.3 28.7 64 64 64l384 0c35.3 0 64-28.7 64-64l0-80c0-35.3-28.7-64-64-64l-64.8 0-48 48L448 352c8.8 0 16 7.2 16 16l0 80c0 8.8-7.2 16-16 16L64 464c-8.8 0-16-7.2-16-16l0-80c0-8.8 7.2-16 16-16l112.8 0-48-48zM432 408a24 24 0 1 0 -48 0 24 24 0 1 0 48 0z"></path></svg>';
                                    break;
                                    case 'pdf_url':
                                        $dataCodeLabel = 'View PDF';
                                        $dataIcon = '<svg class="icon-attribute" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M64 464l48 0 0 48-48 0c-35.3 0-64-28.7-64-64L0 64C0 28.7 28.7 0 64 0L229.5 0c17 0 33.3 6.7 45.3 18.7l90.5 90.5c12 12 18.7 28.3 18.7 45.3L384 304l-48 0 0-144-80 0c-17.7 0-32-14.3-32-32l0-80L64 48c-8.8 0-16 7.2-16 16l0 384c0 8.8 7.2 16 16 16zM176 352l32 0c30.9 0 56 25.1 56 56s-25.1 56-56 56l-16 0 0 32c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-48 0-80c0-8.8 7.2-16 16-16zm32 80c13.3 0 24-10.7 24-24s-10.7-24-24-24l-16 0 0 48 16 0zm96-80l32 0c26.5 0 48 21.5 48 48l0 64c0 26.5-21.5 48-48 48l-32 0c-8.8 0-16-7.2-16-16l0-128c0-8.8 7.2-16 16-16zm32 128c8.8 0 16-7.2 16-16l0-64c0-8.8-7.2-16-16-16l-16 0 0 96 16 0zm80-112c0-8.8 7.2-16 16-16l48 0c8.8 0 16 7.2 16 16s-7.2 16-16 16l-32 0 0 32 32 0c8.8 0 16 7.2 16 16s-7.2 16-16 16l-32 0 0 48c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-64 0-64z"></path></svg>';
                                    break;
                                    case 'sinch_videos':
                                        $dataCodeLabel = 'View Video';
                                        $dataIcon = '<svg class="icon-attribute" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M73 39c-14.8-9.1-33.4-9.4-48.5-.9S0 62.6 0 80L0 432c0 17.4 9.4 33.4 24.5 41.9s33.7 8.1 48.5-.9L361 297c14.3-8.7 23-24.2 23-41s-8.7-32.2-23-41L73 39z"/></svg>';
                                    break;
                                    default:
                                }       
                                foreach($urlsArray as $url){
                                    echo "<a target='_blank' href=" . $url . ">" . $dataIcon . $dataCodeLabel . "</a><br/>";
                                }
                            ?>
                        </td>
                    </tr>
                <?php else: ?>
                    <tr>
                        <th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
                        <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>"><?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                    </tr> 
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>
