<?php
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\Block */

$product = $block->getProduct();
$bulletPoints = $product->getData('sinch_bullet_points');
$_title = $block->getData('title');
if($_title){
    echo '<h3>' . $_title . '</h3>';
}
if (!empty($bulletPoints)):
    echo "<div class='sitc-bullet-points'><ul>";
    foreach (explode("|||", $bulletPoints) as $bulletPoint) {
        echo "<li>" . $bulletPoint . "</li>";
    }
    echo "</ul></div>";
endif;
