<?php
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\Block */

$product = $block->getProduct();
if (!$product) return;

$summaryFeatures = [];
for ($i = 1; $i <= 4; $i++) {
    $title = $product->getData("sinch_summary_title_{$i}");
    $value = $product->getData("sinch_summary_value_{$i}");
    if (empty($title) || empty($value)) continue;
    $summaryFeatures[] = $title . ": " . $value;
}
if (!empty($summaryFeatures)) {
    echo "<div class='sitc-summary-features'><ul>";
    foreach ($summaryFeatures as $feature) {
        echo "<li>" . $feature . "</li>";
    }
    echo "</ul></div>";
}
