<?php

use Magento\Catalog\Block\Product\ListProduct;
use SITC\Sinchimport\Helper\Badges;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();

$badgeHelper = $this->helper('SITC\Sinchimport\Helper\Badges');
$badgeProducts = $badgeHelper->loadCachedBadgeProducts($_productCollection);
?>
<?php
$counter = 0;
$indexes = [];
?>
<?php foreach ($_productCollection as $_product): ?>
    <?php foreach (array_keys(Badges::BADGE_TYPES) as $badgeType):?>
        <?php $badgeTypeProductId = $badgeProducts[$badgeType] ?? -1; ?>
        <?php if ($badgeTypeProductId != -1 && $_product->getId() == $badgeTypeProductId): ?>
            <?php $indexes[] = $counter; ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php $counter++; ?>
<?php endforeach; ?>

<script>
    const productsImages = document.querySelectorAll('.products.list .product-item-photo');
    let indexes = [];
    <?php foreach ($indexes as $index):?>
        indexes.push(<?= $index ?>);
    <?php endforeach; ?>
    indexes.forEach (index => {
        productsImages[index].innerHTML = "test";
    });
</script>

<style>
    .badge-custom{
        width: 75px;
        display: inline;
        position: absolute;
        left: 0;
        color: #fff;
        padding: 7px 10px;
        z-index: 2;
        top: 0;
    }
    .badge-1 {
        /*background: #11a924; */
    }
    a.product-item-photo {
        position: relative;
    }
</style>
